# Generated by Django 5.0.6 on 2024-07-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_parkingspot_spot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='size',
            field=models.CharField(choices=[('compact', 'Compact'), ('regular', 'Regular'), ('electric', 'Electric')], max_length=15),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_type',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
