# Generated by Django 5.0.6 on 2024-06-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='spot_type',
            field=models.CharField(choices=[('compact', 'Compact'), ('regular', 'Regular'), ('electric', 'Electric')], default='compact', max_length=15),
            preserve_default=False,
        ),
    ]
